@startuml
'https://plantuml.com/component-diagram

"User" as user

interface UserCLI

component ClientContext

component Banking

component CardGenerator

database "User Database" as DB

folder Entities {
  component Card
}

user --> UserCLI
UserCLI --> ClientContext
ClientContext --> Banking
ClientContext --> CardGenerator
ClientContext --> DB

Banking --> Entities
CardGenerator --> Entities
DB --> Entities

@enduml